# Generated by Django 2.0 on 2018-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180115_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pinterest link'),
        ),
    ]
