# Generated by Django 2.0 on 2018-01-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_instagram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram link'),
        ),
    ]
