# Generated by Django 2.0 on 2018-01-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
    ]
