# Generated by Django 2.0 on 2018-01-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
