# Generated by Django 2.0 on 2018-01-16 03:44

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180115_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
