# Generated by Django 2.0 on 2018-01-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.CharField(blank=True, default='static/assets/images/gl-11.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
