# Generated by Django 2.0 on 2018-01-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180113_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
