# Generated by Django 2.0 on 2018-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img_src',
            field=models.CharField(max_length=500),
        ),
    ]
