# Generated by Django 2.0 on 2018-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180102_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
