# Generated by Django 2.0 on 2018-01-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='img_src',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
