# Generated by Django 2.0 on 2018-01-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20180111_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='filtered_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/%d/filtered'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
    ]
